source(file.path("R", "00_packages.R"), local = TRUE)
source(file.path("R", "helpers_uploads.R"), local = TRUE)
source(file.path("R", "helpers_merge.R"), local = TRUE)
source(file.path("R", "helpers_queue.R"), local = TRUE)
source(file.path("R", "helpers_mutation.R"), local = TRUE)
source(file.path("R", "helpers_nuclease.R"), local = TRUE)
source(file.path("R", "helpers_manifests.R"), local = TRUE)
source(file.path("R", "helpers_messages.R"), local = TRUE)
source(file.path("R", "ui_sidebar.R"), local = TRUE)
source(file.path("R", "ui_home.R"), local = TRUE)
source(file.path("R", "ui_components.R"), local = TRUE)
source(file.path("R", "ui_merge.R"), local = TRUE)
source(file.path("R", "ui_mutation.R"), local = TRUE)
source(file.path("R", "ui_nuclease.R"), local = TRUE)
source(file.path("R", "ui_main.R"), local = TRUE)
source(file.path("R", "server_settings.R"), local = TRUE)
source(file.path("R", "server_merge.R"), local = TRUE)
source(file.path("R", "server_mutation.R"), local = TRUE)
source(file.path("R", "server_nuclease.R"), local = TRUE)
source(file.path("R", "server.R"), local = TRUE)

ui <- build_ui()

shinyApp(ui = ui, server = server)
