##################
# Function Setup #
##################

# ------------
# readSettings
# ------------

# make example settings data.frame
make.set.df <- function() {
  data.frame(Name = "test",
             IsAntibody = TRUE,
             MergedFASTQPath = file.path(tempdir(), "test-merged.fastq.gz"),
             ReferenceSequence = "GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCT",
             ForwardExtensionType = "Barcode",
             ForwardExtension = "GCTAGCC",
             ForwardPrimer = "GTAAAACGACGGCCAGT",
             ReverseExtensionType = "UMI",
             ReverseExtension = "NNNYRNNNYRNN",
             ReversePrimer = "CAGGAAACAGCTATGAC",
             AmpliconLength = 395L,
             InsertStart = 25L,
             InsertEnd = -30L,
             FR1Start = 1L,
             CDR1Start = 73L,
             FR2Start = 97L,
             CDR2Start = 148L,
             FR3Start = 172L,
             CDR3Start = 286L,
             FR4Start = 310L,
             FR4End = 342L)
}


# ----------
# ShortReadQ
# ----------



makeFakeSRQ <- function(seqs) {
  qs <- Biostrings::BStringSet(vapply(Biostrings::width(seqs), function(len) paste(rep("I", len), collapse = ""), character(1)))
  ids <- Biostrings::BStringSet(replicate(n = length(seqs), fakeIlluminaId()))
  ShortRead::ShortReadQ(sread = seqs, quality = qs, id = ids)
}


# -------------
# tas.sequences
# -------------


fakeIlluminaId <- function() {
  stringr::str_c("A90033:281:WB24762987th.Miseq:1:", sample(100:50000, 1), ":", sample(100:50000, 1), ":AAGAGGCA+CGGAGAGA")
}


makeTestSequences <- function(test.settings) {
  seqs <-  c("GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCT",
             "GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTATTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGGAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCT",
             "GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGT----TTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCT",
             "GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGA",
             "GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATAGTTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCT",
             "GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATAGTTATTGTAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCT",
             "GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGT----TTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCT")
  count <-  c(2, 1, 1, 1, 1, 1, 1)
  pct <-  c(25, 12.5, 12.5, 12.5, 12.5, 12.5, 12.5)
  ind <-  c("WT", "", "-4", "-5", "+1", "+1", "+1, -4")
  bc <-  c(0, 2, 0, 0, 0, 1, 0)
  aa <-  c("VQLVESGGALVQPGGSLRLSCAASGFPVNRYSMRWYRQAPGKEREWVAGMSSAGDRSSYEDSVKGRFTISRDDARNTVYLQMNSLKPEDTAVYYCNVNVGFEYWGQGTQVTVSS",
           "VQLVESGGALVQPGGSLRLSCAASGFPVNRYSMRWYRQAPGKEREWVAGMRSAGDRSSYEDSVKGRFTISRDDARNTVYLQMNSLKPEDTAVYYCNVNVGFEYWGQGTQVTVSS",
           "VQLVESGGALVQPGGSLRLSCAASGFPVNRYSMRWYRQAPGKEREWVAGMSSAGDRSSYEDSVKGRFTISRDDARNTVYLQMNSLKPEDTAVYYCNVN-",
           "VQLVESGGALVQPGGSLRLSCAASGFPVNRYSMRWYRQAPGKEREWVAGMSSAGDRSSYEDSVKGRFTISRDDARNTVYLQMNSLKPEDTAVYYCNVNVGFEYWGQGTQVTV-",
           "VQLVESGGALVQPGGSLRLSCAASGFPVNRYSMRWYRQAPGKEREWVAGMSSAGDRSSYEDSVKGRFTISRDDARNTVYLQMNSLKPEDTAV+",
           "VQLVESGGALVQPGGSLRLSCAASGFPVNRYSMRWYRQAPGKEREWVAGMSSAGDRSSYEDSVKGRFTISRDDARNTVYLQMNSLKPEDTAV+",
           "VQLVESGGALVQPGGSLRLSCAASGFPVNRYSMRWYRQAPGKEREWVAGMSSAGDRSSYEDSVKGRFTISRDDARNTVYLQMNS+")

  pm <-  c("WT", "S51R", "Indel", "Indel", "Indel", "Indel", "Indel")



  t <- data.frame(Sequences = seqs,
                  Count = count,
                  Percent = pct,
                  Indels = ind,
                  BasesChanged = bc,
                  AA = aa,
                  ProteinMutation = pm)

  s <- data.table(Index = as.integer(1:length(seqs)),
                  UMIs = list((c("AGCGAATTAGAG", "CTCGAATTAGTA")), "TTTAGCGCGTAG", "GGCGTATTAACC", "CATGTGGCACGC", "CTTATGACGCTC", "TCCAGGGTATTC", "CTTAGGGCATGT"),
                  IDs = list(list(c(replicate(33, fakeIlluminaId())), c(replicate(24, fakeIlluminaId()))),
                             c(replicate(11, fakeIlluminaId())),
                             c(replicate(8, fakeIlluminaId())),
                             c(replicate(7, fakeIlluminaId())),
                             c(replicate(6, fakeIlluminaId())),
                             c(replicate(4, fakeIlluminaId())),
                             c(replicate(3, fakeIlluminaId()))),
                  IndelStart = as.numeric(c(NA_real_, NA_real_, 297, 338, 279, 279, 255)),
                  IndelType = c(NA_character_, NA_character_, "deletion", "deletion", "insertion", "insertion", "insertion")
  )

  dss <- Biostrings::DNAStringSet(stringr::str_remove_all(seqs, "-"))
  da <- pwalign::pairwiseAlignment(dss, Biostrings::DNAStringSet(test.settings@ReferenceSequence))
  pa <- pwalign::pairwiseAlignment(Biostrings::AAStringSet(aa), Biostrings::AAStringSet(suppressWarnings(Biostrings::translate(Biostrings::DNAString(test.settings@ReferenceSequence)))))
  ReadCounts <- c(Merged = 118L, Filtered = 98L, UMIs = 8L, UniqueSequences = 7L)

  new("tas.sequences", Table = t, Supplemental = s, Alignments = list(DNA = da, AA = pa), ReadCounts = ReadCounts)
}

# -------------
# tas.mutations
# -------------


makeTestMutation <- function() {
  all.dna <- data.frame(Position = sort(c(as.numeric(1:342), 255.5, 279.5)),
                        MutationFrequency = rep(0, 344))
  all.dna$MutationFrequency[c(93, 153, 256, 281, 287, 299, 300, 301, 302, 303)] <- c(12.5, 12.5, 12.5, 25, 12.5, 12.5, 25, 25, 25, 12.5)

  cyt <- data.frame(Position = c(7, 25, 26, 31, 34, 37, 44, 59, 60, 65, 74, 87, 93, 105, 122, 139, 143, 146, 152, 153, 173, 187, 203, 210, 230, 234, 240, 241, 249, 259, 274, 284, 285, 300, 338, 339),
                    MutationFrequency = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.5, 0, 0, 0, 0, 0, 0, 12.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.5, 25, 0, 0))

  ncyt <- data.frame(Position = sort(c(as.numeric(1:342), 255.5, 279.5)
                                    )[!sort(c(as.numeric(1:342), 255.5, 279.5)) %in%
                                       c(7, 25, 26, 31, 34, 37, 44, 59, 60, 65, 74, 87, 93, 105, 122, 139, 143, 146, 152, 153, 173, 187, 203, 210, 230, 234, 240, 241, 249, 259, 274, 284, 285, 300, 338, 339)],
                    MutationFrequency = rep(0, 308))
  ncyt$MutationFrequency[c(227, 250, 266, 267, 268, 269)] <- c(12.5, 25, 12.5, 25, 25, 12.5)

  ms <- c(AverageAllMutations = 0.5087209,
          AverageCytosineMutations = 1.7361111,
          AverageNonCytosineMutations = 0.3652597,
          FrequencyOfAllMutationsAtCytosines = 35.7142857,
          FrequencyOfAllMutationsAtNonCytosines = 64.2857143)

  all.aa <- data.frame(Position = 1:114, MutationFrequency = rep(0, 114))
  all.aa$MutationFrequency[c(51, 85, 93, 99, 112)] <- c(12.5, 12.5, 25, 12.5, 12.5)

  mm.aa <- matrix(0, 30, 114)
  mm.aa[c(1502, 2549, 2789, 2968, 3358)] <- c(12.5, 12.5, 25, 12.5, 12.5)
  rownames(mm.aa) <- c('A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V', 'U', 'O', 'B', 'J', 'Z', 'X', '*', '-', '+', '.')

  aidt.h <- data.frame(Motif = c('WRCH', 'WRCH', 'DGYW', 'DGYW', 'WRCH', 'WRCH', 'DGYW', 'WRCH', 'DGYW', 'WRCH', 'DGYW', 'WRCH', 'WRCH', 'DGYW', 'DGYW', 'DGYW', 'WRCH', 'DGYW', 'WRCH', 'DGYW', 'DGYW', 'DGYW', 'WRCH', 'WRCH', 'WRCH', 'DGYW', 'WRCH', 'DGYW', 'WRCH', 'WRCH', 'DGYW', 'WRCH', 'DGYW', 'DGYW', 'WRCH', 'DGYW'),
                       Start = c(5, 24, 24, 30, 32, 35, 43, 58, 58, 63, 73, 85, 91, 104, 121, 138, 141, 145, 151, 151, 172, 186, 201, 208, 228, 233, 239, 239, 247, 257, 273, 283, 283, 299, 337, 337),
                       End = c(8, 27, 27, 33, 35, 38, 46, 61, 61, 66, 76, 88, 94, 107, 124, 141, 144, 148, 154, 154, 175, 189, 204, 211, 231, 236, 242, 242, 250, 260, 276, 286, 286, 302, 340, 340),
                       Cytosine = c(7, 26, 25, 31, 34, 37, 44, 60, 59, 65, 74, 87, 93, 105, 122, 139, 143, 146, 153, 152, 173, 187, 203, 210, 230, 234, 241, 240, 249, 259, 274, 285, 284, 300, 339, 338),
                       CytosineMutationFrequency = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.5, 0, 0, 0, 0, 0, 0, 12.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.5, 25, 0, 0)
                       )
  aidt.y <- data.frame(Motif = c('WRCY', 'WRCY', 'RGYW', 'WRCY', 'RGYW', 'WRCY', 'RGYW', 'WRCY', 'RGYW', 'WRCY', 'WRCY', 'RGYW', 'RGYW', 'RGYW', 'WRCY', 'RGYW', 'RGYW', 'RGYW', 'WRCY', 'WRCY', 'WRCY', 'RGYW', 'RGYW', 'WRCY', 'RGYW'),
                       Start = c(5, 24, 30, 35, 43, 58, 58, 63, 73, 85, 91, 104, 121, 138, 141, 145, 151, 172, 208, 228, 257, 273, 299, 337, 337),
                       End = c(8, 27, 33, 38, 46, 61, 61, 66, 76, 88, 94, 107, 124, 141, 144, 148, 154, 175, 211, 231, 260, 276, 302, 340, 340),
                       Cytosine = c(7, 26, 31, 37, 44, 60, 59, 65, 74, 87, 93, 105, 122, 139, 143, 146, 152, 173, 210, 230, 259, 274, 300, 339, 338),
                       CytosineMutationFrequency = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0)
  )

  new("tas.mutations", DNA = list(AllMutations = all.dna, CytosineMutations = cyt, NonCytosineMutations = ncyt, MotifSums = ms),
      AA = list(AllMutations = all.aa, MutationMatrix = mm.aa),
      AIDTables = list(WRCH = aidt.h, WRCY = aidt.y))
}


# --------------
# tas.dna.repair
# --------------

makeTestMutationTypes <- function() {
  new("tas.dna.repair", WT = 25, NHEJ = 12.5, MMEJ = 25, BaseChange = 12.5, IndelBaseChange = 12.5, Other = 12.5)
}


##################
# Variable Setup #
##################


# -------------------------------
# Write a test .csv settings file
# -------------------------------

dfset <- make.set.df()
write.csv(dfset, file = file.path(tempdir(), "settings.csv"), row.names = FALSE)

write.csv(rbind(dfset, dfset), file = file.path(tempdir(), "settings-batch.csv"), row.names = FALSE)



# ----------------------------------
# Build a tas.object.settings object
# ----------------------------------

test.settings <- buildSettings(Name = "test",
                               IsAntibody = TRUE,
                               MergedFASTQPath = file.path(tempdir(), "test-merged.fastq.gz"),
                               ReferenceSequence = "GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCT",
                               ForwardExtensionType = "Barcode",
                               ForwardExtension = "GCTAGCC",
                               ForwardPrimer = "GTAAAACGACGGCCAGT",
                               ReverseExtensionType = "UMI",
                               ReverseExtension = "NNNYRNNNYRNN",
                               ReversePrimer = "CAGGAAACAGCTATGAC",
                               AmpliconLength = 395L,
                               InsertStart = 25L,
                               InsertEnd = -30L,
                               FR1Start = 1L,
                               CDR1Start = 73L,
                               FR2Start = 97L,
                               CDR2Start = 148L,
                               FR3Start = 172L,
                               CDR3Start = 286L,
                               FR4Start = 310L,
                               FR4End = 342L)


# --------------------------------
# Make a test tas.sequences object
# --------------------------------

test.seq <- makeTestSequences(test.settings)


# --------------------------------
# Write a simulated .fastq.gz file
# --------------------------------

srq.test <- makeFakeSRQ(Biostrings::DNAStringSet(c(rep("GCTAGCCGTAAAACGACGGCCAGTGTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCTGTCATAGCTGTTTCCTGAGCGAATTAGAG", 33),  # WT            AGCGAATTAGAG
                                  rep("GCTAGCCGTAAAACGACGGCCAGTGTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCTGTCATAGCTGTTTCCTGCTCGAATTAGTA", 24),  # WT            CTCGAATTAGTA
                                  rep("GCTAGCCGTAAAACGACGGCCAGTGTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTATTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGGAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCTGTCATAGCTGTTTCCTGTTTAGCGCGTAG", 11),  # 2 base change TTTAGCGCGTAG
                                  rep("GCTAGCCGTAAAACGACGGCCAGTGTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCTGTCATAGCTGTTTCCTGGGCGTATTAACC", 8),       # -4, internal  GGCGTATTAACC
                                  rep("GCTAGCCGTAAAACGACGGCCAGTGTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGTCATAGCTGTTTCCTGCATGTGGCACGC", 7),        # -5, 3' end    CATGTGGCACGC
                                  rep("GCTAGCCGTAAAACGACGGCCAGTGTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATAGTTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCTGTCATAGCTGTTTCCTGCTTATGACGCTC", 6),  # +1 insertion  CTTATGACGCTC
                                  rep("GCTAGCCGTAAAACGACGGCCAGTGTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATAGTTATTGTAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCTGTCATAGCTGTTTCCTGTCCAGGGTATTC", 4),  # +1 ins, 1 bc  TCCAGGGTATTC
                                  rep("GCTGTAAAACGACGGCCAGTGTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCTGTCATAGCTGTTTCCTGAATAAGTCATTA", 8),       # f primer del  AATAAGTCATTA
                                  rep("GCTAGCCGTAAAACGACGGCCAGTGTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCTGTCATAGCTTCCTGCCCATCACAAAG", 4),      # r primer del  CCCATCACAAAG
                                  rep("GCTAGCCGTAAAACGACGGCCAGTGTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCTGTCATAGCTGTTTCCTGGGCGTGAAAGAG", 5),   # umi error     GGCGTGAAAGAG
                                  rep("GCTACCCGTAAAACGACGGCCAGTGTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCTGTCATAGCTGTTTCCTGCCTAACTCAGGA", 3),   # barcode error CCTAACTCAGGA
                                  rep("GCTAGCCGTAAAACGACGGCCAGTGTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCTGTCATAGCTGTTTCCTGCTTAGGGCATGT", 3),      # -4, +1        CTTAGGGCATGT
                                  rep("GCTAGCCGTAAAACGACGGCCAGTGTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCTGTCATAGCTGTTTCCTGGTTATGTTGTTA", 2)    # < reads       GTTATGTTGTTA
)))
if (file.exists(file.path(tempdir(), "test-merged.fastq.gz"))) {file.remove(file.path(tempdir(), "test-merged.fastq.gz"))}
ShortRead::writeFastq(srq.test, file = file.path(tempdir(), "test-merged.fastq.gz"))


srq.test.lowdiv <- makeFakeSRQ(Biostrings::DNAStringSet(rep("GCTAGCCGTAAAACGACGGCCAGTGTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCTGTCATAGCTGTTTCCTGAGCGAATTAGAG", 33)))
if (file.exists(file.path(tempdir(), "test-merged-lowdiv.fastq.gz"))) {file.remove(file.path(tempdir(), "test-merged-lowdiv.fastq.gz"))}
ShortRead::writeFastq(srq.test.lowdiv, file = file.path(tempdir(), "test-merged-lowdiv.fastq.gz"))





