# # ----------------
# # Helper functions
# # ----------------
#
# test.settings <- buildSettings(Name = "test",
#                                IsAntibody = TRUE,
#                                MergedFASTQPath = file.path(tempdir(), "test-merged.fastq.gz"),
#                                ReferenceSequence = "GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCT",
#                                ForwardExtensionType = "Barcode",
#                                ForwardExtension = "GCTAGCC",
#                                ForwardPrimer = "GTAAAACGACGGCCAGT",
#                                ReverseExtensionType = "UMI",
#                                ReverseExtension = "NNNYRNNNYRNN",
#                                ReversePrimer = "CAGGAAACAGCTATGAC",
#                                AmpliconLength = 395L,
#                                InsertStart = 25L,
#                                InsertEnd = -30L,
#                                FR1Start = 1L,
#                                CDR1Start = 73L,
#                                FR2Start = 97L,
#                                CDR2Start = 148L,
#                                FR3Start = 172L,
#                                CDR3Start = 286L,
#                                FR4Start = 310L,
#                                FR4End = 342L)
#
#
# fakeIlluminaId <- function() {
#   str_c("A90033:281:WB24762987th.Miseq:1:", sample(100:50000, 1), ":", sample(100:50000, 1), ":AAGAGGCA+CGGAGAGA")
# }
#
# makeTestSequences <- function(test.settings) {
#   seqs <-  c("GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCT",
#              "GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTATTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGGAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCT",
#              "GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGT----TTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCT",
#              "GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGA",
#              "GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATAGTTATTGCAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCT",
#              "GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTGAAGCCGGAGGACACCGCAGTATAGTTATTGTAATGTCAACGTGGGGTTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCT",
#              "GTTCAACTGGTGGAAAGCGGCGGTGCTCTGGTACAACCGGGCGGTAGTCTGCGCCTGAGCTGTGCCGCAAGCGGTTTCCCAGTCAACCGCTACTCTATGCGTTGGTATCGCCAGGCGCCTGGTAAAGAACGTGAATGGGTTGCCGGCATGAGCAGTGCGGGCGATCGTTCTAGTTACGAGGACTCTGTTAAAGGTCGTTTTACAATTAGCCGTGATGATGCGCGCAATACCGTGTATCTGCAAATGAACAGTCTTGAAGCCGGAGGACACCGCAGTATATTATTGCAATGTCAACGT----TTTGAATATTGGGGCCAGGGGACTCAGGTGACGGTGAGCTCT")
#   count <-  c(2, 1, 1, 1, 1, 1, 1)
#   pct <-  c(25, 12.5, 12.5, 12.5, 12.5, 12.5, 12.5)
#   ind <-  c("WT", "", "-4", "-5", "+1", "+1", "+1, -4")
#   bc <-  c(0, 2, 0, 0, 0, 1, 0)
#   aa <-  c("VQLVESGGALVQPGGSLRLSCAASGFPVNRYSMRWYRQAPGKEREWVAGMSSAGDRSSYEDSVKGRFTISRDDARNTVYLQMNSLKPEDTAVYYCNVNVGFEYWGQGTQVTVSS",
#            "VQLVESGGALVQPGGSLRLSCAASGFPVNRYSMRWYRQAPGKEREWVAGMRSAGDRSSYEDSVKGRFTISRDDARNTVYLQMNSLKPEDTAVYYCNVNVGFEYWGQGTQVTVSS",
#            "VQLVESGGALVQPGGSLRLSCAASGFPVNRYSMRWYRQAPGKEREWVAGMSSAGDRSSYEDSVKGRFTISRDDARNTVYLQMNSLKPEDTAVYYCNVNVLNIGARGLR*",
#            "VQLVESGGALVQPGGSLRLSCAASGFPVNRYSMRWYRQAPGKEREWVAGMSSAGDRSSYEDSVKGRFTISRDDARNTVYLQMNSLKPEDTAVYYCNVNVGFEYWGQGTQVTV",
#            "VQLVESGGALVQPGGSLRLSCAASGFPVNRYSMRWYRQAPGKEREWVAGMSSAGDRSSYEDSVKGRFTISRDDARNTVYLQMNSLKPEDTAV*",
#            "VQLVESGGALVQPGGSLRLSCAASGFPVNRYSMRWYRQAPGKEREWVAGMSSAGDRSSYEDSVKGRFTISRDDARNTVYLQMNSLKPEDTAV*",
#            "VQLVESGGALVQPGGSLRLSCAASGFPVNRYSMRWYRQAPGKEREWVAGMSSAGDRSSYEDSVKGRFTISRDDARNTVYLQMNSLEAGGHRSILLQCQRFEYWGQGTQVTVSS")
#
#   pm <-  c("WT", "S51R", "Nonsense", "Indel", "Nonsense", "Nonsense", "Indel")
#
#
#
#   t <- data.frame(Sequences = seqs,
#                   Count = count,
#                   Percent = pct,
#                   Indels = ind,
#                   BasesChanged = bc,
#                   AA = aa,
#                   ProteinMutation = pm)
#
#   s <- data.table(Index = as.integer(1:length(seqs)),
#                   UMIs = list(list(c("AGCGAATTAGAG", "CTCGAATTAGTA")), list("TTTAGCGCGTAG"), list("GGCGTATTAACC"), list("CATGTGGCACGC"), list("CTTATGACGCTC"), list("TCCAGGGTATTC"), list("CTTAGGGCATGT")),
#                   IDs = list(list(list(replicate(33, fakeIlluminaId())), list(replicate(24, fakeIlluminaId()))),
#                              list(replicate(11, fakeIlluminaId())),
#                              list(replicate(8, fakeIlluminaId())),
#                              list(replicate(7, fakeIlluminaId())),
#                              list(replicate(6, fakeIlluminaId())),
#                              list(replicate(4, fakeIlluminaId())),
#                              list(replicate(3, fakeIlluminaId()))),
#                   IndelStart = as.numeric(c(NA_real_, NA_real_, 297, 338, 279, 279, 255)),
#                   IndelType = c(NA_character_, NA_character_, "deletion", "deletion", "insertion", "insertion", "insertion")
#   )
#
#   dss <- DNAStringSet(str_remove_all(seqs, "-"))
#   da <- pairwiseAlignment(dss, DNAStringSet(test.settings@ReferenceSequence))
#   pa <- pairwiseAlignment(AAStringSet(aa), AAStringSet(suppressWarnings(translate(DNAString(test.settings@ReferenceSequence)))))
#   ReadCounts <- c(Merged = 53L, Filtered = 44L, UMIs = 8L, UniqueSequences = 3L)
#
#   new("tas.sequences", Table = t, Supplemental = s, Alignments = list(DNA = da, AA = pa), ReadCounts = ReadCounts)
# }


# ----------------
# measureDNArepair
# ----------------

test_that("measureDNArepair works", {
  test.seq <- makeTestSequences(test.settings)
  obj <- measureDNArepair(test.seq, test.settings)
  expect_true(class(obj) == "tas.dna.repair")

  dr <- getMutationTypes(obj)
  expect_equal(colnames(dr), c("WT", "NHEJ", "MMEJ", "BaseChange", "IndelBaseChange", "Other"))
  expect_equal(class(dr), "data.frame")
  expect_equal(dr$WT, 25)
  expect_equal(dr$NHEJ, 12.5)
  expect_equal(dr$MMEJ, 25)
  expect_equal(dr$BaseChange, 12.5)
  expect_equal(dr$IndelBaseChange, 12.5)
  expect_equal(dr$Other, 12.5)

  obj.as <- new("AmpliconSequencing", MutationTypes = obj)
  expect_equal(getMutationTypes(obj), getMutationTypes(obj.as))
})


