#' @name tas_analyze
#' @title One-step analysis and export of targeted amplicon sequencing experiments
#' @description
#' Full analysis of a targeted amplicon sequencing experiment on Illumina, starting from R1 and R2 .fastq reads.
#'
#' @param InputFilePath The complete file path of the input .csv file. Make sure all R1 and R2 files are in the same directory.
#' @param config Determines where the function draws the analysis parameters from. 'manual' allows paramaters to be specified in the function, whereas 'shiny' is used by the shiny app.
#' @param shiny.settings A list of function settings set by the shiny app.
#' @param shiny.env A logical (TRUE/FALSE) to tell whether the function is being executed by the shiny app (TRUE) or not (FALSE).
#' @param shiny.fileTable A character vector containing names of files uploaded to the shiny app.
#' @param WorkingDirectory Optional. The path to the folder containing the input .xlsx file and all input .fastq files.
#' @param merge.reads A logical (TRUE/FALSE) to tell whether PANDAseq should be used to merge paired end read files.
#' @param measure.shm A logical (TRUE/FALSE) to tell whether the somatic hypermutation analysis module should be run.
#' @param sequence.alignment.count Enter a whole number value to determine how many sequences to display as multiple sequence alignments. Default value of 10 is recommended, can require significant resources for larger alignments.
#' @param read.frequency.limit If UMIs are not used, sequences will be filtered using this number as the minimum read frequency percentage for a sequence to be included in the analysis. Values of 0.1-0.001 are recommended.
#' @param protein.mutations A logical (TRUE/FALSE) to tell whether mutations in the amino acid sequences should be analyzed.
#' @param PhyloTree A logical (TRUE/FALSE) to tell whether phylogenetic trees should be made for the number of sequences specified by sequence.alignment.count.
#' @param dna.repair.pathways A logical (TRUE/FALSE) to tell whether this is a gene editing experiment and the type of mutations observed should be classified and counted by the likely underlying DNA repair pathway.
#'
#' @returns A list containing tables and graphical analyses generated by the software.
#' @export
tas_analyze <- function(InputFilePath,
                        config = 'manual',
                        shiny.settings = list(),
                        shiny.env = FALSE,
                        shiny.fileTable = character(),
                        WorkingDirectory = NULL,
                        merge.reads = TRUE,
                        measure.shm = FALSE,
                        sequence.alignment.count = 10,
                        read.frequency.limit = 0.001,
                        protein.mutations = FALSE,
                        PhyloTree = FALSE,
                        dna.repair.pathways = FALSE,
                        multicore = TRUE){
  config <- match.arg(config,c('shiny','manual'))

  if (file.exists(InputFilePath)==FALSE){
    stop("Specified input file not found.")
  }

  #quick set used during debugging
  manual.settings <- list(WorkingDirectory=tempdir(),
                          merge.reads = TRUE,
                          measure.shm = TRUE,
                          sequence.alignment.count = 10,
                          read.frequency.limit = 0.001,
                          protein.mutations = TRUE,
                          PhyloTree = TRUE,
                          dna.repair.pathways = TRUE,
                          multicore = TRUE,
                          shiny.settings = list(),
                          shiny.env = FALSE,
                          shiny.fileTable = character())

  t0 <- Sys.time()
  original.WD <- getwd()
  #work in temp directory
  WD <- paste0(tempdir(),"/")
  if (dir.exists(paste0(WD,"logs"))==FALSE){
    dir.create(paste0(WD,"logs"))
  }
  file.create(paste0(WD,"logs/tasAnalyzer logs.txt"), overwrite = TRUE)
  cat("Working directory set.", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)



  ###############################
  #### LOAD/INSTALL PACKAGES ####
  ###############################

  cat("\nLoading dependencies  (step 1 of 8)...", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)

  suppressMessages(tas_load_dependencies())

  if (shiny.env){
    incProgress(amount = 1/90, message = 'Importing (step 2 of 8)')
  }

  input.dir <- substr(InputFilePath,1,str_locate(InputFilePath,"Input.csv")[,"start"]-1)

  t1 <- Sys.time()
  cat(str_c("Dependencies loaded. Elapsed time: ",format(t1-t0, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)

  ################
  #### IMPORT ####
  ################

  cat("\nImporting  (step 2 of 8)...", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)

  NGS <- list()
  NGS <- tas_import(InputFilePath,config)

  # if (config == 'manual'){
  #   NGS$Config <- c(NGS$Config,list(
  #                      merge.reads=merge.reads,
  #                      measure.shm=measure.shm,
  #                      sequence.alignment.count=sequence.alignment.count,
  #                      read.frequency.limit=read.frequency.limit,
  #                      protein.mutations=protein.mutations,
  #                      PhyloTree=PhyloTree,
  #                      dna.repair.pathways=dna.repair.pathways,
  #                      multicore=multicore,
  #                      nCores=availableCores()))
  # }

  if (config == 'shiny'){
    cat("Setting shiny settings", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
    #fix the import that changes logical values into character vectors
    idx_logical <- intersect(which(!is.na(unlist(lapply(shiny.settings,as.logical)))),
                             suppressWarnings(which(is.na(unlist(lapply(shiny.settings,as.numeric))))))
    shiny.settings[idx_logical] <- lapply(shiny.settings[idx_logical],as.logical)
    NGS$Config <- shiny.settings
  }else{cat("Non-shiny environment. Shiny settings not set.", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)}

  if (NGS$Config$multicore!=TRUE){
    NGS$Config$nCores <- 1
  }

  Sample.Names <- NGS$Input$SampleName
  row.names(NGS$Input) <- Sample.Names

  Reference.Sequences.DNA <- list()
  Reference.Sequences.DNA[Sample.Names] <- lapply(NGS$Input$ReferenceSequence,DNAString)

  if (shiny.env){
    incProgress(amount = 1/90, message = 'Checking files (step 3 of 8)')
  }

  t2 <- Sys.time()

  cat(str_c("Import done. Elapsed time: ",format(t2-t1, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)

  ############################
  #### INPUT FORMAT CHECK ####
  ############################

  cat("\nChecking files (step 3 of 8)...", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)

  tas_check(InputFilePath,NGS$Input, NGS$Config, shiny.env, shiny.fileTable, WD)

  if (shiny.env){
    incProgress(amount = 1/90, message = 'Merging paired-end reads (step 4 of 8)')
  }
  t3 <- Sys.time()
  cat(str_c("Input format check passed. Elapsed time: ", format(t3-t2, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)

  ####################
  ##### PANDASEQ #####
  ####################

  cat("\nMerging paired-end reads  (step 4 of 8)...", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)

  if (NGS$Config$merge.reads==1){
    if (NGS$Config$OperatingSystem %in% c("MacOS","Linux")){
      cat("Attempting PANDAseq through shell terminal...", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
      tas_pandaseq_terminal(Sample.Names, NGS$Input, NGS$Config, WD, shiny.env, shiny.fileTable)
      cat("PANDAseq complete.", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
      Fastq_File_Path <- sapply(Sample.Names,function(x){str_c(WD,"merged/",x,"-merged.fastq.gz")})
      cat("Names of merged files generated.", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
    }else if (NGS$Config$OperatingSystem=="Windows"){
      stop("PANDAseq is not functional on Windows. Please find an alternative approach to merge unpaired reads. See README.md for more information.")
      # tas_pandaseq_windows(Sample.Names, NGS$Input, NGS$Config, WD, shiny.env, shiny.fileTable, original.WD)
      # print("tas_pandaseq_windows done")
      # Fastq_File_Path <- sapply(Sample.Names,function(x){str_c(WD,"merged/",x,"-merged.fastq.gz")})
      # print("fastqfilepath windows done")
    }
  }else if (NGS$Config$merge.reads==FALSE){
    if (dir.exists(str_c(WD,"merged"))==FALSE){
      dir.create(str_c(WD,"merged"))
    }
    merged.empty <- !nzchar(NGS$Input$MergedFASTQFileName)
    if (any(merged.empty)){
      NGS$Input$MergedFASTQFileName[merged.empty] <- str_c("merged/",Sample.Names[merged.empty],"-merged.fastq.gz")
    }
    file.copy(str_c(input.dir,NGS$Input$MergedFASTQFileName),str_c(WD,NGS$Input$MergedFASTQFileName))
    Fastq_File_Path <- sapply(seq_along(Sample.Names),function(x){str_c(WD,NGS$Input$MergedFASTQFileName[x])})
    cat("PANDAseq bypassed. Names of merged files generated.")
  }else{
    stop("merge.reads is not a logical vector. Too confused to continue.")
  }
  cat("\nReading merged files...", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)

  Reads.List <- tas_import_fastq(Sample.Names, Fastq_File_Path)
  t4 <- Sys.time()
  cat(str_c("FASTQ files merged and imported. Elapsed time: ",format(t4-t3, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)

  if (shiny.env){
    incProgress(amount = 2/30, message = 'Filtering, counting, and aligning sequences (step 5 of 8)')
  }

  ########################
  ##### FILTER READS #####
  ########################

  cat("\nFiltering, counting, and aligning sequences  (step 5 of 8)...", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)

  cat("Performing initial filtering by primers (and/or barcode and/or UMI pattern)...", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
  Reads.Filtered.List <- tas_filter(Sample.Names, Reads.List, NGS$Input, NGS$Config)
  Reads.List <- NULL
  t5 <- Sys.time()
  cat(str_c("Initial filtering complete. Elapsed time: ",format(t5-t4, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)

  Sequence.Table.List <- tas_seq_table(Sample.Names, Reads.Filtered.List, NGS$Input, NGS$Config)
  t6 <- Sys.time()
  cat(str_c("Filtering complete and sequence tables generated. Elapsed time: ",format(t6-t5, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
  tas_write_filtered(Sample.Names, Reads.Filtered.List, NGS$Config, WD)
  t7 <- Sys.time()
  cat(str_c("Filtered FASTQ files written and compressed. Elapsed time: ",format(t7-t6, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
  Sequence.Table.List <- tas_label_table(Sample.Names, Sequence.Table.List, Reference.Sequences.DNA, NGS$Input, NGS$Config)
  t8 <- Sys.time()
  cat(str_c("Sequence tables labeled. Elapsed time: ",format(t8-t7, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
  Read.Filter.Count <- tas_filter_count(Sample.Names, Reads.Filtered.List, Sequence.Table.List, NGS$Input, NGS$Config, WD)
  write.xlsx(Read.Filter.Count,str_c(WD,"logs/Filtering.xlsx"),rowNames=TRUE,overwrite = TRUE)
  Reads.Filtered.List <- NULL
  t9 <- Sys.time()
  cat(str_c("Read filtration counted and written to logs/Filtering.xlsx. Elapsed time: ",format(t9-t8, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)

  if (shiny.env){
    incProgress(amount = 12/30, message = 'Measuring mutations (step 6 of 8)')
  }

  cat(str_c("Step 5 complete. Total elapsed time: ",format(t9-t4, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)


  #############################
  ##### MEASURE MUTATIONS #####
  #############################

  cat("\nMeasuring mutations  (step 6 of 8)...", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
  if (NGS$Config$measure.shm==1){
    AID.Targets <- tas_find_AID_Targets(Sample.Names, Reference.Sequences.DNA, NGS$Config)
    cat("AID targets identified.", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
  }else{
    AID.Targets <- list()
    cat("AID targets not identified due to settings.", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
  }

  Output.Mutations.List <- tas_measure_mutations(Sample.Names, Sequence.Table.List, AID.Targets, NGS$Input, NGS$Config)
  t10 <- Sys.time()
  cat(str_c("Mutations measured. Elapsed time: ",format(t10-t9, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)

  if (shiny.env){
    incProgress(amount = 2/30, message = 'Performing multiple sequence alignments (step 7 of 8)')
  }


  ###############################
  ##### SEQUENCE ALIGNMENTS #####
  ###############################

  cat("\nPerforming multiple sequence alignments  (step 7 of 8)...", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
  Output.MSA.List <- tas_msa(Sample.Names, Sequence.Table.List, NGS$Input, NGS$Config)
  t11 <- Sys.time()
  cat(str_c("MSA complete. Elapsed time: ",format(t11-t10, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)

  if (shiny.env){
    incProgress(amount = 5/30, message = 'Exporting (step 8 of 8)')
  }

  #############################
  ##### GRAPHS AND EXPORT #####
  #############################

  cat("\nExporting (step 8 of 8)...", file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
  tas_export_msa(Sample.Names, Output.MSA.List, NGS$Config,WD)
  t12 <- Sys.time()
  cat(str_c("MSA files generated. Elapsed time: ",format(t12-t11, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
  Output.Mutations.List <- tas_export_mutations(Sample.Names, Output.Mutations.List, Sequence.Table.List, Reference.Sequences.DNA, NGS$Input, NGS$Config, WD)
  t13 <- Sys.time()
  cat(str_c("Graphs generated and tables exported. Elapsed time: ",format(t13-t12, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
  Results <- list(Sequences=Sequence.Table.List, Mutations=Output.Mutations.List, MSA=Output.MSA.List)

  zip::zipr(zipfile = "analyzed.zip",
            files = str_c(WD,c("Export","filtered","logs","merged")),
            root = WD)

  if (shiny.env){
    incProgress(amount = 8/30, message = 'Done!')
  }else{
    file.copy(file.path(WD,"analyzed.zip"),
                str_c(substr(InputFilePath,1,str_locate(InputFilePath,"Input.csv")[,"start"]-1),"analyzed.zip"),
                      overwrite = TRUE)
  }
  t14 <- Sys.time()

  cat(str_c("ZIP archive of results generated. Elapsed time: ",format(t14-t13, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)
  tf <- Sys.time()
  cat(str_c("\nAnalysis complete. Total elapsed time: ",format(tf-t0, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/tasAnalyzer logs.txt"), sep = "\n", append = TRUE)

  return(Results)
}
