#' @name tas_analyze
#' @title One-step analysis and export of targeted amplicon sequencing experiments
#' @description
#' Full analysis of a targeted amplicon sequencing experiment on Illumina, starting from R1 and R2 .fastq reads.
#'
#' @param InputFilePath The complete file path of the input .csv file. Make sure all R1 and R2 files are in the same directory.
#' @param config Determines where the function draws the analysis parameters from. 'manual' allows paramaters to be specified in the function, whereas 'shiny' is used by the shiny app.
#' @param shiny.settings A list of function settings set by the shiny app.
#' @param shiny.env A logical (TRUE/FALSE) to tell whether the function is being executed by the shiny app (TRUE) or not (FALSE).
#' @param shiny.fileTable A character vector containing names of files uploaded to the shiny app.
#' @param WorkingDirectory Optional. The path to the folder containing the input .xlsx file and all input .fastq files.
#' @param PandaseqDirectory Optional. The path to the folder containing the pandaseq.exe files for use on Windows. Not currently implemented.
#' @param merge.reads A logical (TRUE/FALSE) to tell whether PANDAseq should be used to merge paired end read files.
#' @param measure.shm A logical (TRUE/FALSE) to tell whether the somatic hypermutation analysis module should be run.
#' @param sequence.alignment.count Enter a whole number value to determine how many sequences to display as multiple sequence alignments. Default value of 10 is recommended, can require significant resources for larger alignments.
#' @param read.frequency.limit If UMIs are not used, sequences will be filtered using this number as the minimum read frequency percentage for a sequence to be included in the analysis. Values of 0.1-0.001 are recommended.
#' @param protein.mutations A logical (TRUE/FALSE) to tell whether mutations in the amino acid sequences should be analyzed.
#' @param PhyloTree A logical (TRUE/FALSE) to tell whether phylogenetic trees should be made for the number of sequences specified by sequence.alignment.count.
#' @param dna.repair.pathways A logical (TRUE/FALSE) to tell whether this is a gene editing experiment and the type of mutations observed should be classified and counted by the likely underlying DNA repair pathway.
#'
#' @returns A list containing tables and graphical analyses generated by the software.
#' @export
tas_analyze <- function(InputFilePath,
                        config = 'manual',
                        shiny.settings = list(),
                        shiny.env = FALSE,
                        shiny.fileTable = character(),
                        WorkingDirectory = NULL,
                        PandaseqDirectory = NULL,
                        merge.reads = TRUE,
                        measure.shm = FALSE,
                        sequence.alignment.count = 10,
                        read.frequency.limit = 0.001,
                        protein.mutations = FALSE,
                        PhyloTree = FALSE,
                        dna.repair.pathways = FALSE,
                        multicore = TRUE){
  config <- match.arg(config,c('shiny','manual'))

  if (file.exists(InputFilePath)==FALSE){
    stop("Specified input file not found.")
  }

  manual.settings <- list(WorkingDirectory=tempdir(),
                          PandaseqDirectory = NULL,
                          merge.reads = TRUE,
                          measure.shm = FALSE,
                          sequence.alignment.count = 10,
                          read.frequency.limit = 0.001,
                          protein.mutations = FALSE,
                          PhyloTree = FALSE,
                          dna.repair.pathways = FALSE,
                          multicore = TRUE)

  original.WD <- getwd()

  ###############################
  #### LOAD/INSTALL PACKAGES ####
  ###############################

  cat("Loading dependencies  (step 1 of 8)...\n")

  suppressMessages(tas_load_dependencies())

  if (shiny.env){
    incProgress(amount = 1/90, message = 'Importing (step 2 of 8)')
  }

  input.dir <- substr(InputFilePath,1,str_locate(InputFilePath,"Input.csv")[,"start"]-1)

  ################
  #### IMPORT ####
  ################

  cat("Importing  (step 2 of 8)...\n")
  print(config)
  print(class(config))
  print(shiny.settings)
  print(class(shiny.settings))

  NGS <- list()
  NGS <- tas_import(InputFilePath,config)

  if (config == 'manual'){
    NGS$Config <- c(NGS$Config,list(
                       PandaseqDirectory=PandaseqDirectory,
                       merge.reads=merge.reads,
                       measure.shm=measure.shm,
                       sequence.alignment.count=sequence.alignment.count,
                       read.frequency.limit=read.frequency.limit,
                       protein.mutations=protein.mutations,
                       PhyloTree=PhyloTree,
                       dna.repair.pathways=dna.repair.pathways,
                       multicore=multicore,
                       nCores=availableCores()))
  }

  if (config == 'shiny'){
    print("setting shiny settings")
    #fix the import that changes logical values into character vectors
    if (is.null(shiny.settings$PandaseqDirectory)){
      shiny.settings$PandaseqDirectory <- NA
    }
    idx_logical <- intersect(which(!is.na(unlist(lapply(shiny.settings,as.logical)))),
                             suppressWarnings(which(is.na(unlist(lapply(shiny.settings,as.numeric))))))
    shiny.settings[idx_logical] <- lapply(shiny.settings[idx_logical],as.logical)
    shiny.settings["PandaseqDirectory"] <- list(NULL)
    NGS$Config <- shiny.settings
  }else{print("shiny.settings not set")}

  #work in directory specified by NGS_Config
  WD <- NGS$Config$WorkingDirectory
  if (substr(WD,nchar(WD),nchar(WD)) != "/"){
    WD <- str_c(WD,"/")
  }
  print("WD set?")
  print(WD)

  if (NGS$Config$multicore!=TRUE){
    NGS$Config$nCores <- 1
  }
  print("check NGS$Config")
  print(NGS$Config)

  Sample.Names <- NGS$Input$SampleName
  row.names(NGS$Input) <- Sample.Names

  Reference.Sequences.DNA <- list()
  Reference.Sequences.DNA[Sample.Names] <- lapply(NGS$Input$ReferenceSequence,DNAString)

  if (shiny.env){
    incProgress(amount = 1/90, message = 'Checking files (step 3 of 8)')
  }

  print("import done")

  ############################
  #### INPUT FORMAT CHECK ####
  ############################

  cat("Checking files (step 3 of 8)...\n")

  tas_check(InputFilePath,NGS$Input, NGS$Config, shiny.env, shiny.fileTable, WD)

  if (shiny.env){
    incProgress(amount = 1/90, message = 'Merging paired-end reads (step 4 of 8)')
  }
  print("input format check passed")

  ####################
  ##### PANDASEQ #####
  ####################

  cat("Merging paired-end reads  (step 4 of 8)...\n")

  if (NGS$Config$merge.reads==1){
    if (NGS$Config$OperatingSystem %in% c("MacOS","Linux")){
      print("trying tas_pandaseq_terminal")
      tas_pandaseq_terminal(Sample.Names, NGS$Input, NGS$Config, WD, shiny.env, shiny.fileTable)
      print("tas_pandaseq_terminal done")
      Fastq_File_Path <- sapply(Sample.Names,function(x){str_c(WD,"merged/",x,"-merged.fastq.gz")})
      print("fastqfilepath done")
    }else if (NGS$Config$OperatingSystem=="Windows"){
      tas_pandaseq_windows(Sample.Names, NGS$Input, NGS$Config, WD, shiny.env, shiny.fileTable, original.WD)
      print("tas_pandaseq_windows done")
      Fastq_File_Path <- sapply(Sample.Names,function(x){str_c(WD,"merged/",x,"-merged.fastq.gz")})
      print("fastqfilepath windows done")
    }
  }else if (NGS$Config$merge.reads==FALSE){
    if (dir.exists(str_c(WD,"merged"))==FALSE){
      dir.create(str_c(WD,"merged"))
    }
    merged.empty <- !nzchar(NGS$Input$MergedFASTQFileName)
    if (any(merged.empty)){
      NGS$Input$MergedFASTQFileName[merged.empty] <- str_c("merged/",Sample.Names[merged.empty],"-merged.fastq.gz")
    }
    file.copy(str_c(input.dir,NGS$Input$MergedFASTQFileName),str_c(WD,NGS$Input$MergedFASTQFileName))
    Fastq_File_Path <- sapply(seq_along(Sample.Names),function(x){str_c(WD,NGS$Input$MergedFASTQFileName[x])})
    print("fastqfilepath without pandaseq done")
  }else{
    stop("merge.reads is not a logical vector. Too confused to continue.")
  }
  print("reading fastq.gz files")

  Reads.List <- tas_import_fastq(Sample.Names, Fastq_File_Path)
  print("reads.list done")

  if (shiny.env){
    incProgress(amount = 2/30, message = 'Filtering, counting, and aligning sequences (step 5 of 8)')
  }

  ########################
  ##### FILTER READS #####
  ########################

  cat("Filtering, counting, and aligning sequences  (step 5 of 8)...\n")

  Reads.Filtered.List <- tas_filter(Sample.Names, Reads.List, NGS$Input, NGS$Config)
  Reads.List <- NULL
  Sequence.Table.List <- tas_seq_table(Sample.Names, Reads.Filtered.List, NGS$Input, NGS$Config)
  tas_write_filtered(Sample.Names, Reads.Filtered.List, NGS$Config, WD)
  Sequence.Table.List <- tas_label_table(Sample.Names, Sequence.Table.List, Reference.Sequences.DNA, NGS$Input, NGS$Config)
  Read.Filter.Count <- tas_filter_count(Sample.Names, Reads.Filtered.List, Sequence.Table.List, NGS$Input, NGS$Config, WD)
  write.xlsx(Read.Filter.Count,str_c(WD,"logs/Filtering.xlsx"),rowNames=TRUE,overwrite = TRUE)
  Reads.Filtered.List <- NULL

  if (shiny.env){
    incProgress(amount = 12/30, message = 'Measuring mutations (step 6 of 8)')
  }


  #############################
  ##### MEASURE MUTATIONS #####
  #############################

  cat("Measuring mutations  (step 6 of 8)...\n")
  if (NGS$Config$measure.shm==1){
    AID.Targets <- tas_find_AID_Targets(Sample.Names, Reference.Sequences.DNA, NGS$Config)
  }else{
    AID.Targets <- list()
  }

  Output.Mutations.List <- tas_measure_mutations(Sample.Names, Sequence.Table.List, AID.Targets, NGS$Input, NGS$Config)

  if (shiny.env){
    incProgress(amount = 2/30, message = 'Performing multiple sequence alignments (step 7 of 8)')
  }


  ###############################
  ##### SEQUENCE ALIGNMENTS #####
  ###############################

  cat("Performing multiple sequence alignments  (step 7 of 8)...\n")
  Output.MSA.List <- tas_msa(Sample.Names, Sequence.Table.List, NGS$Input, NGS$Config)

  if (shiny.env){
    incProgress(amount = 5/30, message = 'Exporting (step 8 of 8)')
  }

  #############################
  ##### GRAPHS AND EXPORT #####
  #############################

  cat("Exporting (step 8 of 8)...\n")
  tas_export_msa(Sample.Names, Output.MSA.List, NGS$Config,WD)
  Output.Mutations.List <- tas_export_mutations(Sample.Names, Output.Mutations.List, Sequence.Table.List, Reference.Sequences.DNA, NGS$Input, NGS$Config, WD)
  Results <- list(Sequences=Sequence.Table.List, Mutations=Output.Mutations.List, MSA=Output.MSA.List)

  zip::zipr(zipfile = "analyzed.zip",
            files = str_c(WD,c("Export","filtered","logs","merged")),
            root = WD)

  if (shiny.env){
    incProgress(amount = 8/30, message = 'Done!')
  }else{
    file.copy(str_c(WD,"analyzed.zip"),
                str_c(substr(InputFilePath,1,str_locate(InputFilePath,"Input.csv")[,"start"]-1),"analyzed.zip"))
  }

  cat("Done!\n")

  return(Results)
}
