###############################################################################
# measureMutations()
# ------------------

#' Measure mutations
#'
#' @param sequence.table S4 object of class tas.sequences
#' @param settings S4 object of class tas.settings
#'
#'
#' @returns An S4 object of class tas.mutations
#' @export
#'
#' @examples
#' measureMutations(sequence.table, settings)
measureMutations <- function(sequence.table, settings) {
    config <- getSettings(settings)
    t <- getSequenceTable(sequence.table)

    AID.targets <- findAIDtargets(config)

    cat("Measuring DNA mutations...\n")

    wt.dna <- lapply(config$ReferenceSequence,Biostrings::DNAString)
    seq.len <- unique(sapply(wt.dna, Biostrings::nchar))
    ref.idx <- getSequenceSupplemental(sequence.table)$RefIdx
    ref.len <- length(unique(ref.idx))
    if (length(seq.len) > 1) {stop("Reference sequences of different legnths detected. Not currently supported, stopping.")}
    seqs <- Biostrings::DNAStringSet(t$Sequences)

    # rep behaves strangely if the alignment is of length = 1. It will replicate
    # the pattern, but not the artificial quality score generated by the pairwiseAlignment
    # function. This causes a length mismatch error during the mismatchSummary
    # function. A wrapper is applied here to use rep only if there are > 1 sequences
    # in the alignment. If there is only 1 sequence, the percentages should all be
    # 100% in the calculations below and so the actual count should be irrelevant.
    dna.align <- lapply(seq_along(getDNAalign(sequence.table)), function(x) {
      aln <- getDNAalign(sequence.table)[[x]]
      if (length(aln) > 1) {
        return(rep(getDNAalign(sequence.table)[[x]], t$Count[ref.idx == x]))
      } else {
        return(aln)
      }
    })


    ### All Mutations ###
    mut.list <- lapply(1:ref.len, function(x) {

      mm.df <- pwalign::mismatchSummary(dna.align[[x]])$subject
      dt.mm <- data.table(Position = mm.df$SubjectPosition, N = mm.df$Count)

      dt.i <- data.table(Position = (Biostrings::start(BiocGenerics::unlist(pwalign::insertion(dna.align[[x]]))) + 0.5))
      dt.i <- dt.i[, .N, by = Position]
      setorder(dt.i, -N)

      dt.d <- data.table(start = Biostrings::start(BiocGenerics::unlist(pwalign::deletion(dna.align[[x]]))), width = Biostrings::width(BiocGenerics::unlist(pwalign::deletion(dna.align[[x]]))))
      dt.d <- dt.d[, .(start = start, end = (start + width -1))]
      if (!isEmpty(dt.d)){
        dt.d <- dt.d[, .(Position = BiocGenerics::unlist(Map(seq, start, end)))]
        dt.d <- dt.d[, .N, by = Position]
      } else {
        dt.d <- data.table(Position = numeric(), N = integer())
      }


      dt.merge <- rbindlist(list(dt.mm, dt.i, dt.d))[, .(MutationFrequency = sum(N)/sum(t$Count[ref.idx == x])*100), by = Position]
      idx.nz <- dt.merge$Position
      idx.z <- (1:seq.len)[!(1:seq.len %in% idx.nz)]
      dt.merge <- rbind(dt.merge, data.table(Position = idx.z, MutationFrequency = rep(0, length(idx.z))))
      setorder(dt.merge, Position)

      ### (Non)Cytosine Mutations ###

      pos.c <- AID.targets[[x]]$WRCH$Cytosine
      pos.nonc <- (dt.merge$Position)[!(dt.merge$Position %in% pos.c)]

      dt.cyt.mut <- dt.merge[(dt.merge$Position %in% pos.c),]
      dt.ncyt.mut <- dt.merge[(dt.merge$Position %in% pos.nonc),]


      ### Motif Sums ###
      AverageAllMutations <-  mean(dt.merge$MutationFrequency)
      AverageCytosineMutations <-  mean(dt.cyt.mut$MutationFrequency)
      AverageNonCytosineMutations <-  mean(dt.ncyt.mut$MutationFrequency)
      FrequencyOfAllMutationsAtCytosines <- sum(dt.cyt.mut$MutationFrequency)/sum(dt.merge$MutationFrequency)*100
      FrequencyOfAllMutationsAtNonCytosines <- sum(dt.ncyt.mut$MutationFrequency)/sum(dt.merge$MutationFrequency)*100
      if (is.nan(FrequencyOfAllMutationsAtCytosines)) {FrequencyOfAllMutationsAtCytosines <- 0}
      if (is.nan(FrequencyOfAllMutationsAtNonCytosines)) {FrequencyOfAllMutationsAtNonCytosines <- 0}
      ms <- data.table(AverageAllMutations = AverageAllMutations,
                       AverageCytosineMutations = AverageCytosineMutations,
                       AverageNonCytosineMutations = AverageNonCytosineMutations,
                       FrequencyOfAllMutationsAtCytosines = FrequencyOfAllMutationsAtCytosines,
                       FrequencyOfAllMutationsAtNonCytosines = FrequencyOfAllMutationsAtNonCytosines)

      ### Protein Mutations ###

      wt.prot <- suppressWarnings(Biostrings::AAStringSet(Biostrings::translate(wt.dna[[x]])))
      prot.len <- Biostrings::nchar(wt.prot)

      # Same rep filter as above for the dna.align to correct for rep behavior
      # on length = 1 pairwise alignments.
      if (length(getAAalign(sequence.table)[[x]]) > 1) {
        prot.align <- rep(getAAalign(sequence.table)[[x]], t$Count[ref.idx == x])
      } else {
        prot.align <- getAAalign(sequence.table)[[x]]
      }
      ids <- getSequenceSupplemental(sequence.table)$IndelStart[ref.idx == x]
      idt <- getSequenceSupplemental(sequence.table)$IndelType[ref.idx == x]

      dt.p <- as.data.table(pwalign::mismatchSummary(prot.align)$subject)
      if (!isEmpty(dt.p)) {
        dt.p <- dt.p[!Pattern %in% c("-", "+")]
        dt.p <- dt.p[, .(.N, MutationFrequency = sum(Count)/sum(t$Count[ref.idx == x])*100, Position = SubjectPosition), by = SubjectPosition][,c("Position", "MutationFrequency")]
        dt.idp <- data.table(Position = ceiling(ids/3), MutationFrequency = t$Percent[ref.idx == x])
        if (!isEmpty(dt.idp)) {
          dt.idp <- data.table(Position = ceiling(ids/3), MutationFrequency = t$Percent)[!is.na(Position)]
        } else {
          dt.idp <- data.table(Position = numeric(), MutationFrequency = numeric())
        }
      } else {
        dt.p <- data.table(Position = numeric(), MutationFrequency = numeric())
        dt.idp <- data.table(Position = numeric(), MutationFrequency = numeric())
      }
      dt.pl <- rbindlist(list(dt.p, dt.idp,
                              data.table(Position = which(!1:prot.len %in% c(dt.p$Position, dt.idp$Position)), MutationFrequency = rep(0, length(which(!1:prot.len %in% c(dt.p$Position, dt.idp$Position))))))
                         , fill = TRUE)[, .(MutationFrequency = sum(MutationFrequency)), by = Position]

      setorder(dt.pl, Position)

      cm.wt <- pwalign::consensusMatrix(wt.prot)
      cm.prot <- pwalign::consensusMatrix(Biostrings::AAStringSet(rep(getSequencesAA(sequence.table)[ref.idx == x], t$Count[ref.idx == x])))
      cm.prot <- cm.prot/(sum(t$Count[ref.idx == x]))*100
      cm.prot[cm.wt == 1] <- 0

      list(DNA = dt.merge, cytm = dt.cyt.mut, ncytm = dt.ncyt.mut, MS = ms, AA = dt.pl, CM = cm.prot)

    })

    dt.dna.list <- unlist(mut.list, recursive = FALSE)[names(unlist(mut.list, recursive = FALSE)) == "DNA"]
    names(dt.dna.list) <- 1:length(dt.dna.list)
    dt.dna.merge <- rbindlist(dt.dna.list, idcol = TRUE)[, .(MutationFrequency = .mutationFrequencyMerge(MutationFrequency, .id, ref.idx)), by = Position]
    AllMutations <- as.data.frame(dt.dna.merge)

    dt.cytm.list <- unlist(mut.list, recursive = FALSE)[names(unlist(mut.list, recursive = FALSE)) == "cytm"]
    names(dt.cytm.list) <- 1:length(dt.cytm.list)
    dt.cytm.merge <- rbindlist(dt.cytm.list, idcol = TRUE)[, .(MutationFrequency = .mutationFrequencyMerge(MutationFrequency, .id, ref.idx)), by = Position]
    CytosineMutations <- as.data.frame(dt.cytm.merge)

    dt.ncytm.list <- unlist(mut.list, recursive = FALSE)[names(unlist(mut.list, recursive = FALSE)) == "ncytm"]
    names(dt.ncytm.list) <- 1:length(dt.ncytm.list)
    dt.ncytm.merge <- rbindlist(dt.ncytm.list, idcol = TRUE)[, .(MutationFrequency = .mutationFrequencyMerge(MutationFrequency, .id, ref.idx)), by = Position]
    NonCytosineMutations <- as.data.frame(dt.ncytm.merge)

    dt.ms.list <- unlist(mut.list, recursive = FALSE)[names(unlist(mut.list, recursive = FALSE)) == "MS"]
    names(dt.ms.list) <- 1:length(dt.ms.list)
    dt.ms.merge <- rbindlist(dt.ms.list, idcol = TRUE)[, .(AverageAllMutations = .mutationFrequencyMerge(AverageAllMutations, .id, ref.idx),
                                                           AverageCytosineMutations = .mutationFrequencyMerge(AverageCytosineMutations, .id, ref.idx),
                                                           AverageNonCytosineMutations = .mutationFrequencyMerge(AverageNonCytosineMutations, .id, ref.idx),
                                                           FrequencyOfAllMutationsAtCytosines = .mutationFrequencyMerge(FrequencyOfAllMutationsAtCytosines, .id, ref.idx),
                                                           FrequencyOfAllMutationsAtNonCytosines = .mutationFrequencyMerge(FrequencyOfAllMutationsAtNonCytosines, .id, ref.idx))]
    MotifSums <- stats::setNames(as.numeric(dt.ms.merge), colnames(dt.ms.merge))

    dt.wrch.list <-unlist(AID.targets, recursive = FALSE)[names(unlist(AID.targets, recursive = FALSE)) == "WRCH"]
    names(dt.wrch.list) <- 1:length(dt.wrch.list)
    dt.wrch.merge <- rbindlist(dt.wrch.list, idcol = TRUE)[, .(Motif = unique(Motif),
                                                                Start = unique(Start),
                                                                End = unique(End)),
                                                            by = Cytosine]
    setcolorder(dt.wrch.merge, c("Motif", "Start", "End", "Cytosine"))

    dt.wrcy.list <-unlist(AID.targets, recursive = FALSE)[names(unlist(AID.targets, recursive = FALSE)) == "WRCY"]
    names(dt.wrcy.list) <- 1:length(dt.wrcy.list)
    dt.wrcy.merge <- rbindlist(dt.wrcy.list, idcol = TRUE)[, .(Motif = unique(Motif),
                                                               Start = unique(Start),
                                                               End = unique(End)),
                                                           by = Cytosine]
    setcolorder(dt.wrcy.merge, c("Motif", "Start", "End", "Cytosine"))



    ### AID Tables ###
    AID.tables <- list(WRCH = cbind(as.data.frame(dt.wrch.merge), data.frame(CytosineMutationFrequency = dt.dna.merge$MutationFrequency[dt.dna.merge$Position %in% dt.wrch.merge$Cytosine])),
                       WRCY = cbind(as.data.frame(dt.wrcy.merge), data.frame(CytosineMutationFrequency = dt.dna.merge$MutationFrequency[dt.dna.merge$Position %in% dt.wrcy.merge$Cytosine])))
    row.names(AID.tables$WRCH) <- NULL
    row.names(AID.tables$WRCY) <- NULL


    ### Antibody Regions ###
    if (config$IsAntibody) {
      region.coords <- getAntibodyCoordinates(config$AntibodyRegions)
      total.mut <- sum(dt.dna.merge$MutationFrequency)
      region.mut.dev <- sapply(region.coords, function(x) {
        region.mut <- dt.dna.merge[(dt.dna.merge$Position %in% x),"MutationFrequency"]
        (sum(region.mut)/total.mut-length(x)/seq.len)/(length(x)/seq.len)*100 # percent deviation from expected mutation rate if distribution was even across the sequence
      })
    } else {
      region.mut.dev <- c(FR1 = NA_real_, CDR1 = NA_real_, FR2 = NA_real_, CDR2 = NA_real_, FR3 = NA_real_, CDR3 = NA_real_, FR4 = NA_real_)
    }


    dt.aa.list <- unlist(mut.list, recursive = FALSE)[names(unlist(mut.list, recursive = FALSE)) == "AA"]
    names(dt.aa.list) <- 1:length(dt.aa.list)
    dt.aa.merge <- rbindlist(dt.aa.list, idcol = TRUE)[, .(MutationFrequency = .mutationFrequencyMerge(MutationFrequency, .id, ref.idx)), by = Position]
    all.mut.prot <- as.data.frame(dt.aa.merge)

    cm.list <- unlist(mut.list, recursive = FALSE)[names(unlist(mut.list, recursive = FALSE)) == "CM"]

    cm.sum <- Reduce("+", cm.list)



    new("tas.mutations", DNA = list(AllMutations = AllMutations,
                                    CytosineMutations = CytosineMutations,
                                    NonCytosineMutations = NonCytosineMutations,
                                    MotifSums = MotifSums),
                         AA = list(AllMutations = all.mut.prot, # data.frame
                                   MutationMatrix = cm.sum), # matrix
                         AIDTables = AID.tables, # list(WRCH, WRCY)
                         Antibody = list(RegionMutations = region.mut.dev))

}


measureMutationsNuclease <- function(sequence.table, settings) {
  ################################################################
  # TODO: FIX PROBLEM HERE
  # failing on heterozygous input test with invalid times t$count
  # I think this is because the sequenceTable is combined from separate lists
  # so its too long relative to each individual msa.dna to replicate
  #
  # Not sure how to fix right now, need a tas.sequences output that
  # carries over the count statistics while keeping separated with the
  # separate reference sequence lists.
  #######################################
  t <- data.table(Count = getSequenceTable(sequence.table)$Count,
                  RefIdx = getSequenceSupplemental(sequence.table)$RefIdx
                  )
  msa.dna <- getDNAmsa(sequence.table)

  msa.cm.list <- lapply(seq_along(msa.dna), function(x) {
    mat <- Biostrings::as.matrix(msa.dna[[x]])
    wt.mat <- mat[1,]
    msa.mat <- mat[2:nrow(msa.dna[[x]]), ,drop = FALSE]
    msa.mat.all <- msa.mat[rep.int(seq_len(nrow(msa.mat)), t$Count[t$RefIdx == x]), , drop = FALSE]
    msa.cm <- Biostrings::consensusMatrix(msa.mat.all)
    if (all(c("-", "A", "C", "G", "T") %in% rownames(msa.cm))) {
      msa.cm <- msa.cm[c("-", "A", "C", "G", "T"),]
    } else if (all(c("A", "C", "G", "T") %in% rownames(msa.cm)) && !"-" %in% rownames(msa.cm)){
      msa.cm <- rbind(matrix(0, ncol = ncol(msa.cm), dimnames = list("-", NULL)), msa.cm)
    }
    wt.cm <- Biostrings::consensusMatrix(Biostrings::DNAStringSet(stringr::str_flatten(wt.mat)))[c("-", "A", "C", "G", "T"),]
    msa.cm[wt.cm == 1] <- 0
    cm.colnames <- character(ncol(msa.cm))
    pos <- 0
    # TODO: evaluate speed and determine if this R for loop is fast enough, or if it needs to be farmed out to C
    for (i in seq_along(cm.colnames)) {
      if (wt.mat[i] != "-" && pos %% 1 == 0) {
        pos <- pos + 1
      } else if (wt.mat[i] == "-" && pos %% 1 == 0){
        pos <- pos + 0.5
      } else if (wt.mat[i] != "-" && pos %% 1 == 0.5){
        pos <- pos + 0.5
      }

      # do nothing for (wt.cm[i] == "-" && pos %% 1 == 0.5)
      # give same number for consecutive insertions since they're still between the same reference base #'s

      cm.colnames[i] <- pos
    }
    colnames(msa.cm) <- cm.colnames
    return(msa.cm)
  })

  # deal with edge case of different sized matrices if different max insertion
  # size for different ref sequences
  list.colnames <- lapply(msa.cm.list, colnames)
  if (length(unique(list.colnames)) > 1) {
    col.count <- table(unlist(list.colnames))
    col.unique <- names(col.count[col.count < length(list.colnames)])
    for (i in seq_along(list.colnames)) {
      miss <- !(col.unique %in% list.colnames[[i]])
      if (any(miss)) {
        msa.cm.list[[i]] <- cbind(msa.cm.list[[i]], matrix(0,
                                                           nrow = nrow(msa.cm.list[[i]]),
                                                           ncol = length(col.unique[miss]),
                                                           dimnames = list(NULL, col.unique[miss]))
                                  )[,stringr::str_sort(colnames(msa.cm.list[[i]]), numeric = TRUE)]
      }
    }
  }
  msa.cm <- Reduce("+", msa.cm.list)
  msa.cm <- msa.cm/sum(t$Count)*100
  all.mut <- data.frame(Position = as.numeric(colnames(msa.cm)),
                        MutationFrequency = colSums(msa.cm), row.names = NULL)
  output <- new("tas.mutations")
  output@DNA$AllMutations <- all.mut
  return(output)
}



###############################################################################
# Helper functions
# ------

findAIDtargets <- function(settings) {
  if (class(settings) == "tas.object.settings") {
    config <- getSettings(settings)
  } else {
    config <- settings
  }
  if (class(config) != "list") {
    stop("settings must be a tas.object.settings object or a list")
  }

  AID.Motifs <- c("WRCY","RGYW","WRCH","DGYW")
  # aid[AID.Motifs] <- S4Vectors::lapply(AID.Motifs, function(x){

  aid <- S4Vectors::lapply(config$ReferenceSequence, function(seq) {
    t <- rbindlist(S4Vectors::lapply(AID.Motifs, function(m) {
        pat.views <- Biostrings::matchPattern(m, Biostrings::DNAString(seq), fixed = FALSE)
        s <- Biostrings::start(pat.views)
        e <- Biostrings::end(pat.views)

        if (m == "WRCY" | m == "WRCH"){
          cyt <- e-1
        }
        if (m == "RGYW" | m == "DGYW"){
          cyt <- e-2
        }
        data.frame(Motif=rep(m, length(pat.views)), Start=s, End=e, Cytosine=cyt)
      }))

      y.df <- as.data.frame(rbind(t[t$Motif == "WRCY",], t[t$Motif == "RGYW"]))
      y.df <- y.df[order(y.df$Start),]
      h.df <- as.data.frame(rbind(t[t$Motif == "WRCH",], t[t$Motif == "DGYW"]))
      h.df <- h.df[order(h.df$Start),]

      list(WRCH = h.df, WRCY = y.df)
    })

  return(aid) # new structure list(list(WRCH, WRCY), ...)
}


getAntibodyCoordinates <- function(abr) {
  out <- list(length(abr))
  for (i in seq_along(abr)[-length(abr)]) {
    out[[i]] <- abr[i]:(abr[i+1] - 1)
  }
  names(out) <- stringr::str_remove(names(abr), "Start")[-length(abr)]
  return(out)
}


