#' @name tas_pandaseq_wasm
#' @title Helper function for generation of PANDAseq arguments.
#' @description
#' This function generates a list containing a set of arguments for each sample in the input .csv file. Helper function to tas_shiny_args.
#' @param Sample.Names A character vector with names of all samples.
#' @param Input.DataFrame A data frame imported from the .xlsx file specifying details of each sample.
#' @param Config.List A list containing configuration parameters for tasAnalyzer.
#' @param WD A character vector indicating the file path to the working directory containing input files.
#' @param shiny.env A logical (TRUE/FALSE) identifying whether processing is being perfomed by the Shiny app. Assigned by parent functions.
#' @param shiny.fileTable A data.table with information about uploaded files in the Shiny app. Assigned automatically by parent functions.
#' @returns A list where each element contains arguments to feed into the pandaseq function.
#' @export
tas_pandaseq_wasm <- function(Sample.Names, Input.DataFrame, Config.List, WD, shiny.env, shiny.fileTable){
  Input.Columns <- c("SampleName",
                     "ForwardFASTQFileName",
                     "ReverseFASTQFileName",
                     "AmpliconLength",
                     "MaxDeletion",
                     "MaxInsertion")

  Config.Entries <- c("nCores",
                      "merge.reads")

  if(FALSE %in% (Input.Columns %in% colnames(Input.DataFrame))){
    stop(c("The following columns were not found in the input file: ",
           str_flatten(Input.Columns[!Input.Columns %in% colnames(Input.DataFrame)],collapse = ", ")))
  }

  if(FALSE %in% (Config.Entries %in% names(Config.List))){
    stop(c("The following columns were not found in the input file: ",
           str_flatten(Config.Entries[!Config.Entries %in% names(Config.List)],collapse = ", ")))
  }


  #check if export directories exist and create if needed
  if (dir.exists(str_c(WD,"unpaired"))==FALSE){
    dir.create(str_c(WD,"unpaired"))
  }
  if (dir.exists(str_c(WD,"merged"))==FALSE){
    dir.create(str_c(WD,"merged"))
  }
  if (dir.exists(str_c(WD,"logs"))==FALSE){
    dir.create(str_c(WD,"logs"))
  }
  if (shiny.env){
    file.rename(shiny.fileTable$datapath[str_detect(shiny.fileTable$name,".fastq")],
                str_c(WD,"unpaired/",shiny.fileTable$name[str_detect(shiny.fileTable$name,".fastq")]))
  }

  Pandaseq_Args <- list()
  Pandaseq_Args[Sample.Names] <- lapply(seq_along(Sample.Names),function(x){
    c(str_c("-f '",WD,"unpaired/",Input.DataFrame$ForwardFASTQFileName[[x]],"'"),
      str_c("-r '",WD,"unpaired/",Input.DataFrame$ReverseFASTQFileName[[x]],"'"),
      str_c("-g '",WD,"logs/",Sample.Names[[x]],"-pandaseq-log.txt'"),
      "-F",
      "-d bFSrk",
      str_c("-l ",(Input.DataFrame$AmpliconLength[[x]]-Input.DataFrame$MaxDeletion[[x]])),
      str_c("-L ",(Input.DataFrame$AmpliconLength[[x]]+Input.DataFrame$MaxInsertion[[x]])),
      str_c("-w '",WD,"merged/",Sample.Names[[x]],"-merged.fastq'"))
  })

  #error prevention, remove tmp files generated by PANDAseq that remain if the R process is stopped while PANDAseq is running
  merged.files <- sapply(Sample.Names,function(x){
    str_c(WD,"merged/",x,"-merged.fastq.gz.tmp")
  })
  if (any(file.exists(merged.files))){
    file.remove(merged.files[file.exists(merged.files)])
  }

  return(Pandaseq_Args)
}

#' @name tas_shiny_args
#' @title Generate a list pandaseq arguments for the shinylive app.
#' @description
#' This function generates a list containing a set of arguments for each sample in the input .csv file. This is designed to return to the shinylive app, which uses the list to invoke an Enscripten-compiled fork of PANDAseq through a Javascript intermediary.
#' @param InputFilePath The complete file path of the input .csv file. Make sure all R1 and R2 files are in the same directory.
#' @param config Determines where the function draws the analysis parameters from. 'manual' allows paramaters to be specified in the function, whereas 'shiny' is used by the shiny app.
#' @param shiny.settings A list of function settings set by the shiny app.
#' @param shiny.env A logical (TRUE/FALSE) to tell whether the function is being executed by the shiny app (TRUE) or not (FALSE).
#' @param shiny.fileTable A character vector containing names of files uploaded to the shiny app.
#' @returns A list where each element contains arguments to feed into the pandaseq function.
#' @export
tas_shiny_args <- function(InputFilePath,
                            config = 'shiny',
                            shiny.settings = list(),
                            shiny.env = TRUE,
                            shiny.fileTable = character(),
                            WorkingDirectory = NULL){

  if (file.exists(InputFilePath)==FALSE){
    stop("Specified input file not found.")
  }

  WD <- paste0(tempdir(),"/")
  if (dir.exists(paste0(WD,"logs"))==FALSE){
    dir.create(paste0(WD,"logs"))
  }

  file.create(paste0(WD,"logs/shinyMerge logs.txt"))
  cat("Working directory set.", file = paste0(WD,"logs/shinyMerge logs.txt"), sep = "\n", append = TRUE)

  cat("\nLoading dependencies  (step 1 of 8)...", file = paste0(WD,"logs/shinyMerge logs.txt"), sep = "\n", append = TRUE)

  suppressMessages(tas_load_dependencies())

  if (shiny.env){
    incProgress(amount = 1/90, message = 'Importing (step 2 of 8)')
  }

  input.dir <- substr(InputFilePath,1,str_locate(InputFilePath,"Input.csv")[,"start"]-1)

  t1 <- Sys.time()
  cat(str_c("Dependencies loaded. Elapsed time: ",format(t1-t0, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/shinyMerge logs.txt"), sep = "\n", append = TRUE)


  cat("\nImporting  (step 2 of 8)...", file = paste0(WD,"logs/shinyMerge logs.txt"), sep = "\n", append = TRUE)

  NGS <- list()
  NGS <- tas_import(InputFilePath)

  if (config == 'shiny'){
    cat("Setting shiny settings", file = paste0(WD,"logs/shinyMerge logs.txt"), sep = "\n", append = TRUE)
    #fix the import that changes logical values into character vectors
    idx_logical <- intersect(which(!is.na(unlist(lapply(shiny.settings,as.logical)))),
                             suppressWarnings(which(is.na(unlist(lapply(shiny.settings,as.numeric))))))
    shiny.settings[idx_logical] <- lapply(shiny.settings[idx_logical],as.logical)
    NGS$Config <- shiny.settings
  }else{cat("Non-shiny environment. Shiny settings not set.", file = paste0(WD,"logs/shinyMerge logs.txt"), sep = "\n", append = TRUE)}

  if (NGS$Config$multicore!=TRUE){
    NGS$Config$nCores <- 1
  }

  Input.DataFrame <- NGS$Input
  Config.List <- NGS$Config

  Sample.Names <- NGS$Input$SampleName
  row.names(NGS$Input) <- Sample.Names

  Reference.Sequences.DNA <- list()
  Reference.Sequences.DNA[Sample.Names] <- lapply(NGS$Input$ReferenceSequence,DNAString)

  if (shiny.env){
    incProgress(amount = 1/90, message = 'Checking files (step 3 of 8)')
  }

  t2 <- Sys.time()

  cat(str_c("Import done. Elapsed time: ",format(t2-t1, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/shinyMerge logs.txt"), sep = "\n", append = TRUE)

  cat("\nChecking files (step 3 of 8)...", file = paste0(WD,"logs/shinyMerge logs.txt"), sep = "\n", append = TRUE)

  tas_check(InputFilePath,NGS$Input, NGS$Config, shiny.env, shiny.fileTable, WD)

  if (shiny.env){
    incProgress(amount = 1/90, message = 'Merging paired-end reads (step 4 of 8)')
  }
  t3 <- Sys.time()
  cat(str_c("Input format check passed. Elapsed time: ", format(t3-t2, digits = 4, with.units = TRUE)), file = paste0(WD,"logs/shinyMerge logs.txt"), sep = "\n", append = TRUE)

  cat("\nMerging paired-end reads  (step 4 of 8)...", file = paste0(WD,"logs/shinyMerge logs.txt"), sep = "\n", append = TRUE)

  pandaseqArgs <- tas_pandaseq_wasm(Sample.Names, Input.DataFrame, Config.List, WD, shiny.env, shiny.fileTable)

  Output <- list(pandaseqArgs = pandaseqArgs,
                 Input.DataFrame = Input.DataFrame,
                 Config.List = Config.List,
                 Sample.Names = Sample.Names,
                 WD = WD,
                 InputFilePath = InputFilePath)

  return(Output)
}




